// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_studio.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO ai_studio_chats (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateChatParams struct {
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (AiStudioChat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.UserID, arg.Title)
	var i AiStudioChat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO ai_studio_messages (chat_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, role, content, created_at
`

type CreateMessageParams struct {
	ChatID  int64  `json:"chat_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (AiStudioMessage, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.Role, arg.Content)
	var i AiStudioMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChatForUser = `-- name: DeleteChatForUser :execrows
DELETE FROM ai_studio_chats
WHERE id = $1 AND user_id = $2
`

type DeleteChatForUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteChatForUser(ctx context.Context, arg DeleteChatForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllChatsForUser = `-- name: GetAllChatsForUser :many
SELECT id, user_id, title, created_at, updated_at FROM ai_studio_chats
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetAllChatsForUser(ctx context.Context, userID string) ([]AiStudioChat, error) {
	rows, err := q.db.Query(ctx, getAllChatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiStudioChat
	for rows.Next() {
		var i AiStudioChat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatForUser = `-- name: GetChatForUser :one
SELECT id, user_id, title, created_at, updated_at FROM ai_studio_chats
WHERE id = $1 AND user_id = $2
`

type GetChatForUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetChatForUser(ctx context.Context, arg GetChatForUserParams) (AiStudioChat, error) {
	row := q.db.QueryRow(ctx, getChatForUser, arg.ID, arg.UserID)
	var i AiStudioChat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT id, chat_id, role, content, created_at FROM ai_studio_messages
WHERE chat_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMessagesByChat(ctx context.Context, chatID int64) ([]AiStudioMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiStudioMessage
	for rows.Next() {
		var i AiStudioMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChat = `-- name: TouchChat :exec
UPDATE ai_studio_chats SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchChat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchChat, id)
	return err
}
