// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: egolifter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEgolifterChat = `-- name: CreateEgolifterChat :one
INSERT INTO egolifter_chats (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateEgolifterChatParams struct {
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) CreateEgolifterChat(ctx context.Context, arg CreateEgolifterChatParams) (EgolifterChat, error) {
	row := q.db.QueryRow(ctx, createEgolifterChat, arg.UserID, arg.Title)
	var i EgolifterChat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEgolifterMessage = `-- name: CreateEgolifterMessage :one
INSERT INTO egolifter_messages (chat_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, role, content, created_at
`

type CreateEgolifterMessageParams struct {
	ChatID  int64  `json:"chat_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) CreateEgolifterMessage(ctx context.Context, arg CreateEgolifterMessageParams) (EgolifterMessage, error) {
	row := q.db.QueryRow(ctx, createEgolifterMessage, arg.ChatID, arg.Role, arg.Content)
	var i EgolifterMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEgolifterChatForUser = `-- name: DeleteEgolifterChatForUser :execrows
DELETE FROM egolifter_chats
WHERE id = $1 AND user_id = $2
`

type DeleteEgolifterChatForUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteEgolifterChatForUser(ctx context.Context, arg DeleteEgolifterChatForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEgolifterChatForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllEgolifterChatsForUser = `-- name: GetAllEgolifterChatsForUser :many
SELECT id, user_id, title, created_at, updated_at FROM egolifter_chats
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetAllEgolifterChatsForUser(ctx context.Context, userID string) ([]EgolifterChat, error) {
	rows, err := q.db.Query(ctx, getAllEgolifterChatsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EgolifterChat
	for rows.Next() {
		var i EgolifterChat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEgolifterChatForUser = `-- name: GetEgolifterChatForUser :one
SELECT id, user_id, title, created_at, updated_at FROM egolifter_chats
WHERE id = $1 AND user_id = $2
`

type GetEgolifterChatForUserParams struct {
	ID     int64  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetEgolifterChatForUser(ctx context.Context, arg GetEgolifterChatForUserParams) (EgolifterChat, error) {
	row := q.db.QueryRow(ctx, getEgolifterChatForUser, arg.ID, arg.UserID)
	var i EgolifterChat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEgolifterMessagesByChat = `-- name: ListEgolifterMessagesByChat :many
SELECT id, chat_id, role, content, created_at FROM egolifter_messages
WHERE chat_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListEgolifterMessagesByChat(ctx context.Context, chatID int64) ([]EgolifterMessage, error) {
	rows, err := q.db.Query(ctx, listEgolifterMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EgolifterMessage
	for rows.Next() {
		var i EgolifterMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchEgolifterChat = `-- name: TouchEgolifterChat :exec
UPDATE egolifter_chats SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchEgolifterChat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchEgolifterChat, id)
	return err
}
