// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1::uuid, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

// Returns the number of rows removed. A result of 0 means the token was not in
// the store (already revoked, already rotated, or never valid), which callers
// use as the single-use / revocation gate. Expiry is enforced separately by the
// JWT layer before this is called, so deleting purely by hash is safe.
func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
