// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, user_id, first_name, last_name, date_of_birth, height_cm, weight_kg, created_at, updated_at FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, first_name, last_name, height_cm, weight_kg)
VALUES ($1::uuid,
        $2,
        $3,
        $4,
        $5)
ON CONFLICT (user_id) DO UPDATE
SET first_name = EXCLUDED.first_name,
    last_name  = EXCLUDED.last_name,
    height_cm  = EXCLUDED.height_cm,
    weight_kg  = EXCLUDED.weight_kg,
    updated_at = now()
RETURNING id, user_id, first_name, last_name, date_of_birth, height_cm, weight_kg, created_at, updated_at
`

type UpsertUserProfileParams struct {
	UserID    string        `json:"user_id"`
	FirstName pgtype.Text   `json:"first_name"`
	LastName  pgtype.Text   `json:"last_name"`
	HeightCm  pgtype.Float8 `json:"height_cm"`
	WeightKg  pgtype.Float8 `json:"weight_kg"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.HeightCm,
		arg.WeightKg,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.WeightKg,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
